{
 "title": "Channel Jamming Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Failed Payments",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "failed_payments", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Pending HTLCs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "pending_htlcs", "legendFormat": "{{pod}}-{{scid}}" }
   ]
  },
  {
   "title": "Channel Balance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "lnd_balance_channels", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Blockchain Height",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "expr": "lnd_block_height", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}